services:
  helperbot:
    build:
      context: .
    container_name: helperbot
    env_file:
      - .env
    restart: always
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - .git/
            - __pycache__/
            - .venv/
